In [1]:
import numpy as np


---
# Types of matrices
---

In [59]:
# square matrix
S = np.random.randn(5, 5)
# Rectangle matrix
R = np.random.randn(5, 2)

# Identity matrix
I = np.eye(4)

# Zero Matrix
O = np.zeros((4, 4))

# Diagonal Matrix
D = np.diag([2, 3, 5, 6, 0, 4, -1])

# Triangular matrix
## Upper triangle
U = np.triu(S)
L = np.tril(S)

# Concatinated Matrices
A = np.random.randn(3, 2)
B = np.random.randn(3, 1)
C = np.concatenate((A, B), axis=1)
# print(A)
# print(' ')
# print(B)
# print(' ')
# print(C)

[1 4]



---
# Matrix addition and subtraction
---

In [19]:
A = np.random.randn(5, 4)
B = np.random.randn(5, 6)
C = np.random.randn(5, 4)

print(A + C)

[[-0.98331811  3.28958367 -0.34397389 -1.31775816]
 [-1.94522142 -0.42296618 -1.21599143 -1.81005792]
 [-0.05529424 -0.7227441  -0.11550695  0.40899721]
 [ 0.71188402 -1.68650097  0.0154413   0.84280871]
 [ 1.72759199 -0.30556625 -0.27670968  0.06984412]]


In [21]:
# Shifting a matrix
N = 5
l = 0.3
A = np.random.randn(N, N)
C = A + l*np.eye(N)
print(A)
print(' ')
print(C)

[[-1.27890888  1.13960856  1.42142383 -2.01395806 -0.88314575]
 [ 1.87620755 -0.4533128   0.42085091  0.13857658  0.67706071]
 [-0.30871181 -1.00610069 -0.95333448 -1.10647358  0.88649071]
 [ 0.09143991  0.9985919  -1.1761302   0.86594557  0.44108155]
 [-0.10515701  0.85471681  0.8017986  -1.24357448 -1.49949576]]
 
[[-0.97890888  1.13960856  1.42142383 -2.01395806 -0.88314575]
 [ 1.87620755 -0.1533128   0.42085091  0.13857658  0.67706071]
 [-0.30871181 -1.00610069 -0.65333448 -1.10647358  0.88649071]
 [ 0.09143991  0.9985919  -1.1761302   1.16594557  0.44108155]
 [-0.10515701  0.85471681  0.8017986  -1.24357448 -1.19949576]]



---
# Matrix-scalar multiplication
---


In [24]:
B = np.array([[1, 2], [3, 4]])
s = 2
print(s*B)
print(' ')
print(B*s)


[[2 4]
 [6 8]]
 
[[2 4]
 [6 8]]


---
### Code Challange :
### Test whether Matrix multiplication is distributive
### Is matrix scaler multplication is a linear operation
---

In [28]:
M = np.array([[1, 2], [2, 3]])
N = np.array([[2, 4], [4, 5]])
s = 2
A = s * (M + N)
B = s * M + s * N
print(A)
print(' ')
print(B)
print(' ')
print(A-B)

[[ 6 12]
 [12 16]]
 
[[ 6 12]
 [12 16]]
 
[[0 0]
 [0 0]]


---
# Transpose
---

In [40]:
M = np.array([[1, 2, 3],
              [3, 4 ,5]
             ])
print(M)
print(' ')
print(M.T.T)
print(' ')
print(M.T)
print(' ')
print(np.transpose(M))

[[1 2 3]
 [3 4 5]]
 
[[1 2 3]
 [3 4 5]]
 
[[1 3]
 [2 4]
 [3 5]]
 
[[1 3]
 [2 4]
 [3 5]]


In [55]:
c = np.array([1+3j, 3-4j, 9+8j])

print(c)
print(' ')
print(np.matrix(c).T)
print(' ')
print(np.matrix(c).H)
print(' ')
print(np.transpose(np.conjugate(c)))

[1.+3.j 3.-4.j 9.+8.j]
 
[[1.+3.j]
 [3.-4.j]
 [9.+8.j]]
 
[[1.-3.j]
 [3.+4.j]
 [9.-8.j]]
 
[1.-3.j 3.+4.j 9.-8.j]



---
# VIDEO: Diagonal and trace
---


In [75]:
# Diagonal
F = np.round( 5 * np.random.randn(4, 4))
d = np.diag(F)
print(f'd : {d}')
print(' ')
print(d)
print(' ')
print(np.diag(d))
print(' ')

d : [ 1.  1.  6. -2.]
 
[ 1.  1.  6. -2.]
 
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  6.  0.]
 [ 0.  0.  0. -2.]]
 


In [78]:
# Trace
F = np.round( 5 * np.random.randn(4, 4))
print(F)
print(' ')
d = np.diag(F)
print(d)
print(' ')
print(np.trace(F))
print(' ')
# Computing trace of a matrix
print(sum(np.diag(F)))

[[-4. -5.  9. -5.]
 [ 5.  3. -4. -1.]
 [ 1.  3.  2.  4.]
 [-6.  5.  6. -0.]]
 
[-4.  3.  2. -0.]
 
1.0
 
1.0


--- 
## code challange: linearity of trace (closed under addition and multiplication
---

In [84]:
A = np.round(5 * np.random.randn(3, 3))
B = np.round(6 * np.random.randn(3, 3))

print(A)
print(' ')
print(B)
print(' ')
print(np.trace(A) + np.trace(B))
print(' ')
print(np.trace(A+B))
print(' ')

[[  1.   2.   5.]
 [ -8.  -2.   3.]
 [  5.   1. -10.]]
 
[[ 0. -9. -5.]
 [ 4.  6. -6.]
 [-2.  7. -4.]]
 
-9.0
 
-9.0
 


In [85]:
A = np.round(5 * np.random.randn(3, 3))
l = 3
print(A)
print(' ')
print(l * np.trace(A))
print(' ')
print(np.trace(l * A))

[[  1.  -7.  -3.]
 [ -2.   3. -14.]
 [  3.   5.  -7.]]
 
-9.0
 
-9.0


---
# Broadcasting matrix arithmetic
---

In [92]:
A = np.reshape(np.arange(1, 13), (3, 4), 'F')
print(A)
r = [100, 200, 300, 400]
c = [100, 200, 300]

print(' ')
print(A + r)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
 
[[101 204 307 410]
 [102 205 308 411]
 [103 206 309 412]]


In [97]:
print(A + np.reshape(c,(len(c), 1)))

[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]


In [98]:
np.reshape(c, (len(c), 1))

array([[100],
       [200],
       [300]])

In [99]:
np.reshape([100, 200, 300], (3,1))

array([[100],
       [200],
       [300]])